all: tetris tetromino driver2 run

tetris: tetris.java
	javac tetris.java

tetromino: tetromino.java
	javac tetromino.java

driver2: driver2.java
	javac driver2.java

run:
	java driver2

clean:
	rm -f *.class
